spring.application.name=fraud-ai-agent

spring.ai.azure.openai.api-key=#${AZURE_OPENAI_API_KEY}
spring.ai.azure.openai.endpoint=#${AZURE_OPENAI_ENDPOINT}
spring.ai.azure.openai.chat.model=gpt-4o
spring.ai.azure.openai.embedding.model=text-embedding-ada-002

spring.datasource.url=#${AZURE_DATASOURCE}
spring.datasource.username=azureuser
spring.datasource.azure.passwordless-enabled=true
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.schema-name=postgres
server.port=8090
spring.ai.mcp.server.name=fraud-mcp-server
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.sse-message-endpoint=/mcp/message
spring.ai.mcp.server.sse-endpoint=/sse
azure.cosmos.uri=#${AZURE_COSMOS_URI}
azure.cosmos.auth=#${AZURE_COSMOS_KEY}
azure.cosmos.database=#${AZURE_COSMOS_DB}
azure.cosmos.populate-query-metrics=true


mcp.client.url=http://localhost:8090/client/findFraudTransactions
mcp.server.url=http://localhost:8090/server/get-transactions

