spring.application.name=fraud-ai-agent

spring.ai.azure.openai.api-key=cda2ee1194534125acd3b84a8caea6c6 
#${AZURE_OPENAI_API_KEY}
spring.ai.azure.openai.endpoint=https://westus3.api.cognitive.microsoft.com/
spring.ai.azure.openai.chat.model=gpt-4o
spring.ai.azure.openai.embedding.model=text-embedding-ada-002

spring.datasource.url=jdbc:postgresql://db-postgres-hemanth-poc.postgres.database.azure.com/postgres?sslmode=require
spring.datasource.username=azureuser
spring.datasource.azure.passwordless-enabled=true
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.schema-name=postgres
server.port=8090


spring.ai.mcp.server.name=fraud-mcp-server
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.sse-message-endpoint=/mcp/message
spring.ai.mcp.server.sse-endpoint=/sse

azure.cosmos.uri=https://learning-cosmos-instance.documents.azure.com:443/
azure.cosmos.key=4two1HlawCfVGCWEPOwohW2hvuSTT2ulqfkz6f5nMmdbSNZSci5ZqCobCILriqkZ405jJ6d22RWhACDb7LaOyg==
azure.cosmos.database=FraudDetectionDB
azure.cosmos.populate-query-metrics=true